# ========================================
# PEFNet Benchmark Configuration - OPTIMIZED
# ========================================

Data:
  route: './config/benchmark_data'
  alternative_routes:
    - './data/Kvasir-seg'
    - './data/CVC-ClinicDB'
  X_path: 'images'
  Y_path: 'masks'
  
  # Image preprocessing
  img_size: 384  # Increased from 256 to match training
  normalize: true
  resize_method: 'bilinear'

Model:
  model_path: './config/checkpoints/best_model.weights.h5'
  backup_paths:
    - './checkpoints/best_model.weights.h5'
    - './checkpoints/backup_model.weights.h5'
  
  # Architecture settings (match training config)
  model_name: 'efficientnetv2-b1'  # Upgraded from b0
  backbone: 'efficientnetv2-b1'
  use_attention: true
  use_pyramid_pooling: true
  img_channels: 3
  num_classes: 1

Evaluation:
  BATCH_SIZE: 24  # Increased from 8 for faster evaluation
  
  # Test Time Augmentation (TTA) - ENABLED
  use_tta: true
  tta_steps: 8  # Strong TTA for best results
  tta_transforms:
    - 'horizontal_flip'
    - 'vertical_flip' 
    - 'rotate_90'
    - 'rotate_180'
    - 'rotate_270'
    - 'brightness'
    - 'contrast'
    - 'gaussian_noise'
  
  # Post-processing
  use_post_processing: true
  use_crf: true  # Conditional Random Fields
  crf_iterations: 10
  crf_gaussian_weight: 3.0
  crf_bilateral_weight: 5.0
  
  # Morphological operations
  use_morphological_ops: true
  morph_kernel_size: 3
  morph_iterations: 2
  
  # Thresholding optimization
  optimize_threshold: true
  threshold_range: [0.3, 0.7]
  threshold_steps: 21  # Test 21 different thresholds
  
Metrics:
  # Comprehensive evaluation metrics
  primary_metrics:
    - 'dice_coefficient'
    - 'iou_score'
    - 'precision'
    - 'recall'
    - 'f1_score'
  
  secondary_metrics:
    - 'specificity'
    - 'sensitivity'
    - 'accuracy'
    - 'hausdorff_distance'
    - 'surface_distance'
  
  # Advanced metrics
  boundary_metrics:
    - 'boundary_iou'
    - 'boundary_f1'
    - 'edge_accuracy'
  
  # Multi-scale evaluation
  multi_scale_evaluation: true
  eval_scales: [320, 384, 448, 512]

Output:
  # Results saving
  save_predictions: true
  save_overlays: true
  save_metrics_csv: true
  save_detailed_results: true
  
  # Output directories
  predictions_dir: './predictions'
  overlays_dir: './overlays'
  results_dir: './benchmark_results'
  plots_dir: './plots'
  
  # Visualization
  create_result_grids: true
  grid_size: [4, 4]  # 4x4 grid of results
  save_individual_results: true
  
  # Export formats
  prediction_format: 'png'
  overlay_alpha: 0.5
  colormap: 'jet'

Hardware:
  # Memory management for evaluation
  enable_memory_growth: true
  max_memory_limit: 15000  # MB
  
  # Performance optimization
  use_mixed_precision: true
  prefetch_buffer_size: 16  # Larger for evaluation
  num_parallel_calls: 16    # More parallel processing
  
  # GPU utilization
  gpu_memory_fraction: 0.9
  allow_soft_placement: true

Advanced:
  # Ensemble evaluation (if multiple models)
  use_ensemble: false
  ensemble_models: []
  ensemble_weights: []
  
  # Uncertainty estimation
  estimate_uncertainty: false
  monte_carlo_samples: 10
  
  # Progressive evaluation
  progressive_sizes: true
  start_size: 256
  end_size: 512
  size_steps: 4
  
  # Statistical analysis
  compute_confidence_intervals: true
  confidence_level: 0.95
  bootstrap_samples: 1000
  
  # Cross-validation evaluation
  use_cross_validation: false
  cv_folds: 5
  
Kaggle:
  # Kaggle-specific settings
  auto_detect_environment: true
  kaggle_output_dir: '/kaggle/working/results'
  create_submission_file: true
  submission_format: 'csv'
  
  # Competition metrics
  competition_metric: 'dice_coefficient'
  target_score: 0.89  # Target Dice score
  
  # Monitoring
  verbose_evaluation: true
  progress_bar: true
  save_intermediate_results: true

Quality:
  # Quality assessment
  assess_prediction_quality: true
  quality_metrics:
    - 'prediction_confidence'
    - 'edge_sharpness'
    - 'region_consistency'
  
  # Failure case analysis
  analyze_failure_cases: true
  failure_threshold: 0.7  # Dice < 0.7 considered failure
  save_failure_cases: true
