Data:

    img_size: 256
    route:  ./data/Kvasir-seg
    X_path: images
    Y_path: masks
    

Hyperparameter:

    valid_size : 0.2
    test_size : 0.25
    SEED : 1024
    BATCH_SIZE : 128
    epochs : 100
    max_lr: 0.001
    min_lr: 0.000001
    save_weights_only: True

Model:
  save_path: ./checkpoints/best_model.weights.h5
